*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 13.09.2017 at 15:06:22
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZHRUS_D2........................................*
FORM GET_DATA_ZHRUS_D2.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM HRUS_D2 WHERE
(VIM_WHERETAB) .
    CLEAR ZHRUS_D2 .
ZHRUS_D2-MANDT =
HRUS_D2-MANDT .
ZHRUS_D2-US_NAME =
HRUS_D2-US_NAME .
ZHRUS_D2-REP_NAME =
HRUS_D2-REP_NAME .
ZHRUS_D2-BEGDA =
HRUS_D2-BEGDA .
ZHRUS_D2-ENDDA =
HRUS_D2-ENDDA .
ZHRUS_D2-ACTIVE =
HRUS_D2-ACTIVE .
<VIM_TOTAL_STRUC> = ZHRUS_D2.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHRUS_D2 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHRUS_D2.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHRUS_D2-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM HRUS_D2 WHERE
  US_NAME = ZHRUS_D2-US_NAME AND
  REP_NAME = ZHRUS_D2-REP_NAME AND
  BEGDA = ZHRUS_D2-BEGDA .
    IF SY-SUBRC = 0.
    DELETE HRUS_D2 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM HRUS_D2 WHERE
  US_NAME = ZHRUS_D2-US_NAME AND
  REP_NAME = ZHRUS_D2-REP_NAME AND
  BEGDA = ZHRUS_D2-BEGDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR HRUS_D2.
    ENDIF.
HRUS_D2-MANDT =
ZHRUS_D2-MANDT .
HRUS_D2-US_NAME =
ZHRUS_D2-US_NAME .
HRUS_D2-REP_NAME =
ZHRUS_D2-REP_NAME .
HRUS_D2-BEGDA =
ZHRUS_D2-BEGDA .
HRUS_D2-ENDDA =
ZHRUS_D2-ENDDA .
HRUS_D2-ACTIVE =
ZHRUS_D2-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE HRUS_D2 .
    ELSE.
    INSERT HRUS_D2 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHRUS_D2-UPD_FLAG,
STATUS_ZHRUS_D2-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZHRUS_D2.
  SELECT SINGLE * FROM HRUS_D2 WHERE
US_NAME = ZHRUS_D2-US_NAME AND
REP_NAME = ZHRUS_D2-REP_NAME AND
BEGDA = ZHRUS_D2-BEGDA .
ZHRUS_D2-MANDT =
HRUS_D2-MANDT .
ZHRUS_D2-US_NAME =
HRUS_D2-US_NAME .
ZHRUS_D2-REP_NAME =
HRUS_D2-REP_NAME .
ZHRUS_D2-BEGDA =
HRUS_D2-BEGDA .
ZHRUS_D2-ENDDA =
HRUS_D2-ENDDA .
ZHRUS_D2-ACTIVE =
HRUS_D2-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHRUS_D2 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHRUS_D2-US_NAME TO
HRUS_D2-US_NAME .
MOVE ZHRUS_D2-REP_NAME TO
HRUS_D2-REP_NAME .
MOVE ZHRUS_D2-BEGDA TO
HRUS_D2-BEGDA .
MOVE ZHRUS_D2-MANDT TO
HRUS_D2-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'HRUS_D2'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN HRUS_D2 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'HRUS_D2'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
