*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 31.01.2018 at 11:19:03
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZHRV_AWART_COLOR................................*
FORM GET_DATA_ZHRV_AWART_COLOR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHRT_AWART_COLOR WHERE
(VIM_WHERETAB) .
    CLEAR ZHRV_AWART_COLOR .
ZHRV_AWART_COLOR-MANDT =
ZHRT_AWART_COLOR-MANDT .
ZHRV_AWART_COLOR-AWART =
ZHRT_AWART_COLOR-AWART .
ZHRV_AWART_COLOR-STATUS =
ZHRT_AWART_COLOR-STATUS .
ZHRV_AWART_COLOR-COLOR =
ZHRT_AWART_COLOR-COLOR .
    SELECT SINGLE * FROM T554S WHERE
MOABW = '33' AND
SUBTY = ZHRT_AWART_COLOR-AWART AND
ENDDA = '99991231' .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHRV_AWART_COLOR-ATEXT =
T554T-ATEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZHRV_AWART_COLOR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHRV_AWART_COLOR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHRV_AWART_COLOR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHRV_AWART_COLOR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHRT_AWART_COLOR WHERE
  AWART = ZHRV_AWART_COLOR-AWART AND
  STATUS = ZHRV_AWART_COLOR-STATUS .
    IF SY-SUBRC = 0.
    DELETE ZHRT_AWART_COLOR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHRT_AWART_COLOR WHERE
  AWART = ZHRV_AWART_COLOR-AWART AND
  STATUS = ZHRV_AWART_COLOR-STATUS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHRT_AWART_COLOR.
    ENDIF.
ZHRT_AWART_COLOR-MANDT =
ZHRV_AWART_COLOR-MANDT .
ZHRT_AWART_COLOR-AWART =
ZHRV_AWART_COLOR-AWART .
ZHRT_AWART_COLOR-STATUS =
ZHRV_AWART_COLOR-STATUS .
ZHRT_AWART_COLOR-COLOR =
ZHRV_AWART_COLOR-COLOR .
    IF SY-SUBRC = 0.
    UPDATE ZHRT_AWART_COLOR .
    ELSE.
    INSERT ZHRT_AWART_COLOR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHRV_AWART_COLOR-UPD_FLAG,
STATUS_ZHRV_AWART_COLOR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHRV_AWART_COLOR.
  SELECT SINGLE * FROM ZHRT_AWART_COLOR WHERE
AWART = ZHRV_AWART_COLOR-AWART AND
STATUS = ZHRV_AWART_COLOR-STATUS .
ZHRV_AWART_COLOR-MANDT =
ZHRT_AWART_COLOR-MANDT .
ZHRV_AWART_COLOR-AWART =
ZHRT_AWART_COLOR-AWART .
ZHRV_AWART_COLOR-STATUS =
ZHRT_AWART_COLOR-STATUS .
ZHRV_AWART_COLOR-COLOR =
ZHRT_AWART_COLOR-COLOR .
    SELECT SINGLE * FROM T554S WHERE
MOABW = '33' AND
SUBTY = ZHRT_AWART_COLOR-AWART AND
ENDDA = '99991231' .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHRV_AWART_COLOR-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHRV_AWART_COLOR-ATEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHRV_AWART_COLOR-ATEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHRV_AWART_COLOR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHRV_AWART_COLOR-AWART TO
ZHRT_AWART_COLOR-AWART .
MOVE ZHRV_AWART_COLOR-STATUS TO
ZHRT_AWART_COLOR-STATUS .
MOVE ZHRV_AWART_COLOR-MANDT TO
ZHRT_AWART_COLOR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHRT_AWART_COLOR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHRT_AWART_COLOR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHRT_AWART_COLOR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHRV_AWART_COLOR USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHRT_AWART_COLOR-MANDT =
ZHRV_AWART_COLOR-MANDT .
ZHRT_AWART_COLOR-AWART =
ZHRV_AWART_COLOR-AWART .
ZHRT_AWART_COLOR-STATUS =
ZHRV_AWART_COLOR-STATUS .
ZHRT_AWART_COLOR-COLOR =
ZHRV_AWART_COLOR-COLOR .
    SELECT SINGLE * FROM T554S WHERE
MOABW = '33' AND
SUBTY = ZHRT_AWART_COLOR-AWART AND
ENDDA = '99991231' .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHRV_AWART_COLOR-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHRV_AWART_COLOR-ATEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHRV_AWART_COLOR-ATEXT .
    ENDIF.
ENDFORM.
